#!/bin/bash

# 02614 - High-Performance Computing, January 2022
# 
# batch script to run matmult on a decidated server in the hpcintro
# queue
#

#BSUB -J part1
#BSUB -oo part2.out
#BSUB -eo part2.err
#BSUB -q hpcintrogpu
#BSUB -n 16
#BSUB -R "rusage[mem=5120]"
#BSUB -W 60
#BSUB -R "span[hosts=1]"
#BSUB -gpu "num=1" 
####BSUB -gpu "num=1:mode=shared:j_exclusive=yes" 
###bsub -gpu - | "[num=num_gpus[/task | host]] 

EXECUTABLE=poisson

OUTPUT=jac_gpu
EXT="csv"

CORES="26"
MAX_IT="10000"
TOL=1e-2
INIT=0


# start the collect command with the above settings

echo "Size,Iter_max,Tolerance,Walltime,Cores" >> jac_gpu.$EXT
for S in {10..250..10}
do
	OMP_NUM_THREADS=$CORES ./$EXECUTABLE $S $MAX_IT $TOL $INIT>> jac_gpu.$EXT
done